module.exports = 
[
    "Bowser",
    "Senator Armstrong",
    "Viper",
    "Ghost of Lady Comstock",
    "The Brickster",
    "Kai Leng",
    "Vortex Queen",
    "The Alien",
    "Landing on the aircraft carrier",
    "Queen Zeal",
    "Tabuu",
    "Malus",
    "The Airship",
    "Primagen",
    "Majora",
    "King Krusha KRool",
    "Ender Dragon",
    "Crawmerax the Invincible",
    "Vergil",
    "Daud",
    "Shadow Queen",
    "Deathstroke",
    "Matriarch Benezia ",
    "Cyberdemon",
    "Shima Sakon",
    "Atheon",
    "Wiegraf/Velius",
    "King Bohan",
    "Mothrakk",
    "Ivaldi",
    "Kurt Zisa",
    "Guildenstern",
    "The Batomys",
    "Mewtwo",
    "Baal",
    "Hitler",
    "Kerafyrm (a.k.athe Sleeper)",
    "Old King Allant",
    "Nemesis",
    "Lavos",
    "Darksol",
    "Darklurker",
    "Shao Kahn",
    "Deathshead",
    "Rebel Flagship",
    "Seth",
    "Manus, Father of the Abyss",
    "Psycho Mantis",
    "Ultimecia",
    "Spider Mastermind",
    "Shadow of Yharnam",
    "Enchantress",
    "Ginso Tree",
    "Giygas",
    "Yuki-Onna",
    "Silver Knight & Laser Eye",
    "Liquid Snake",
    "Jinpachi",
    "Wood Man",
    "Maneater",
    "Dirge",
    "General Raam",
    "Ares",
    "Spider Guardian",
    "High Dragon",
    "Doom’s Bride",
    "Grim Reaper",
    "Artorias",
    "Culex",
    "Death",
    "Dark Link",
    "The Reaper",
    "Terramorphous the Invincible",
    "Death Egg Robot",
    "Tyrant",
    "Omega Weapon",
    "Lingering Will",
    "Shadow Link",
    "Ornstein and Smough",
    "The End",
    "Ludwig, the Accursed",
    "Crota",
    "Dracula",
    "Goro",
    "Jaws",
    "Riku/Ansem",
    "MBison",
    "Alma",
    "Pandemonium Warden",
    "Fume Knight",
    "Mike Tyson",
    "DrWily’s Yellow Devil",
    "Sephiroth",
    "Flamelurker",
    "Orphan of Kos",
    "Emerald Weapon",
    "“Through the Fire and Flames”",
    "The Nameless King",
    "C’Thun",
    "Skolas"
 ]